### ISSUE TITLE
"t is null" or "t is undefined" when uploading a package

### ISSUE THREAD

**Issue by Jastop** [UpdateHub/updatehub-ce#169]
Sorry if this is a stupid question but I keep getting "t is null" or "t is undefined" whenever I upload a package.
I've tried creating a new VM, updating everything on it but I keep getting it.

**Comment by Alex-T-Stark** [comment]
This issue is present in my environment on the latest master branch 0691cd2

Tested on these browsers:
- Mozilla Firefox 101.0.1
- Google Chrome 103.0.5060.53

With updatehub-ce built from source running on these servers:
|     | arch         | OS           | misc       |
|----|--------------|---------------|------------|
| ❌ | ARMv7    | Raspian    | Raspberry Pi 3B+ |
| ❌ | x86_64    | Fedora 36 |             | 

On the server side, updatehub-ce logs report:
```... method=POST, uri=/api/packages, status=500 error=no multipart boundary param in Content-Type```

[potentially relevant source code at: ui/src/components/PackageList.vue](https://github.com/UpdateHub/updatehub-ce/blob/0691cd24d01a3cd1178a3d50b41ee7d08b2bdbe4/ui/src/components/PackageList.vue#L79)

**Comment by otavio** [comment]
Could you prepare a PR?

**Comment by Alex-T-Stark** [comment]
Good news - #314 fixes the issue in my environment.

**Comment by otavio** [comment]
Fixed in #314. @Alex-T-Stark thanks for letting us know.
